# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# This workflow also try to build swagger specification from jsdoc and validate it.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Multi-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean Install and Build
      run: |
        npm ci
        npm run build --if-present
    - name: Run Jest Test
      run: npm test
    - name: Build Swagger/OpenAPI Specification
      run: npx swagger-jsdoc -o ./swagger.yml -d ./utils/swaggerDef.js ./routes/*.ts
    - name: Validate Swagger/OpenAPI Specification
      uses: mbowman100/swagger-validator-action@1.5
      with:
        files: |
          swagger.yml
