# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# This workflow also try to build swagger specification from jsdoc and validate it.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Multi-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean Install and Build
      run: |
        pnpm install
        cp ./src/config.ts.example ./src/config.ts
        cp ./.env.example ./.env
        pnpm run build
    - name: Run Test
      run: pnpm run testall
    - name: Upload Coverage
      uses: codecov/codecov-action@v1.0.14
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: ihaapi-codecov
